In [5]:
import warnings

# Mute all warnings globally
warnings.filterwarnings("ignore")

# Dynamic Pipeline — `DynamicScenarioGenerator`

Extends the FM and AF baselines **beyond 2070** using **NAI-based (Net Annual Increment) harvest**, and extends the scenario end year to match. Mirrors `tests/examples/dsg_example.py`.

In [6]:
import pandas as pd
from goblin_cbm_runner.dynamic_scenario_generator import DynamicScenarioGenerator

scenario_df = pd.read_csv('../../tests/examples/data/input/scenario_dataframe.csv')
afforest_df = pd.read_csv('../../tests/examples/data/input/cbm_afforestation.csv', index_col=0)

## Run the extended simulation

`dynamic_config` overrides the `DF_config.yaml` defaults. `harvest_ratio=0.75` targets a sustainable 75% of annual growth; `dynamic_years` sets how far past 2070 to continue.

In [7]:
dsg = DynamicScenarioGenerator(
    scenario_data=scenario_df,
    afforestation_data=afforest_df,
    config={'afforest_delay': 5, 'annual_rate_pre_delay': 1200},
    dynamic_config={'harvest_ratio': 0.75, 'dynamic_years': 50},
)

results = dsg.run_flux_simulation()        # extended FM + AF + SC
results.head()

INFO:goblin_cbm_runner.runners.fm_runner:Generating FM input data...
INFO:goblin_cbm_runner.runners.fm_runner:FM input data will be saved to: /home/colm/Dropbox/projects/FORESIGHT/packages/cbm_runner/src/goblin_cbm_runner/data/FM_input
INFO:goblin_cbm_runner.runners.fm_runner:FM input data generated

🚀 Starting FM Simulation...
FM Simulation Complete.
Starting dynamic simulation: 2070 to 2120
  Harvest ratio: 0.75
  Clearfell/thinning split: {'DISTID1': 0.8, 'DISTID2': 0.2}
  Year 2080 complete
  Year 2090 complete
  Year 2100 complete
  Year 2110 complete
  Year 2120 complete
Dynamic simulation complete: 50 years

INFO:goblin_cbm_runner.runners.af_runner:Generating AF input data...
INFO:goblin_cbm_runner.runners.af_runner:AF input data will be saved to: /home/colm/Dropbox/projects/FORESIGHT/packages/cbm_runner/src/goblin_cbm_runner/data/AF_input
INFO:goblin_cbm_runner.runners.af_runner:AF input data generated

Starting AF Simulation...
AF Simulation Complete.
Starting dynamic simulation: 2070 to 2120
  Harvest ratio: 0.75
  Clearfell/thinning split: {'DISTID1': 0.8, 'DISTID2': 0.2}
  Year 2080 complete
  Year 2090 complete
  Year 2100 complete
  Year 2110 complete
  Year 2120 complete
Dynamic simulation complete: 50 years

INFO:goblin_cbm_runner.runners.sc_runner:Generating SC input data for scenario 0...
INFO:goblin_cbm_runner.runners.sc_runner:SC input data will be saved to: /home/colm/Dropbox/projects/FORESIGHT/packages/cbm_runner/src/goblin_cbm_runner/data/SC_input
INFO:goblin_cbm_runner.runners.sc_runner:SC input data generated for scenario 0

Starting Scenario 0 Simulation...

INFO:goblin_cbm_runner.runners.sc_runner:Generating SC input data for scenario 1...
INFO:goblin_cbm_runner.runners.sc_runner:SC input data will be saved to: /home/colm/Dropbox/projects/FORESIGHT/packages/cbm_runner/src/goblin_cbm_runner/data/SC_input

Scenario 0 Simulation Complete.

INFO:goblin_cbm_runner.runners.sc_runner:SC input data generated for scenario 1

Starting Scenario 1 Simulation...
Scenario 1 Simulation Complete.

,Year,AGB,BGB,Deadwood,Litter,Soil,Harvest,Total Ecosystem,Scenario
0,1991,7263.311101,1759.130211,8.504021,343.097664,-1734.363021,0.0,7639.679976,-1
1,1992,22253.850184,5250.505060,52.796405,1556.895918,-5776.696748,0.0,23337.350820,-1
2,1993,44303.328764,10481.865799,175.098926,3892.237344,-8829.050404,0.0,50023.480430,-1
3,1994,69440.947422,17314.024378,424.060031,7326.565980,-11232.248424,0.0,83273.349387,-1
4,1995,102710.631872,25607.246189,844.222681,11850.327134,-14254.706643,0.0,126757.721232,-1

## Baseline only

`run_baseline_flux_simulation()` returns the extended FM + AF baseline without the SC scenarios.

In [8]:
baseline = dsg.run_baseline_flux_simulation()
baseline.head()

INFO:goblin_cbm_runner.runners.fm_runner:Generating FM input data...
INFO:goblin_cbm_runner.runners.fm_runner:FM input data will be saved to: /home/colm/Dropbox/projects/FORESIGHT/packages/cbm_runner/src/goblin_cbm_runner/data/FM_input
INFO:goblin_cbm_runner.runners.fm_runner:FM input data generated

🚀 Starting FM Simulation...
FM Simulation Complete.
Starting dynamic simulation: 2070 to 2120
  Harvest ratio: 0.75
  Clearfell/thinning split: {'DISTID1': 0.8, 'DISTID2': 0.2}
  Year 2080 complete
  Year 2090 complete
  Year 2100 complete
  Year 2110 complete
  Year 2120 complete
Dynamic simulation complete: 50 years

INFO:goblin_cbm_runner.runners.af_runner:Generating AF input data...
INFO:goblin_cbm_runner.runners.af_runner:AF input data will be saved to: /home/colm/Dropbox/projects/FORESIGHT/packages/cbm_runner/src/goblin_cbm_runner/data/AF_input
INFO:goblin_cbm_runner.runners.af_runner:AF input data generated

Starting AF Simulation...
AF Simulation Complete.
Starting dynamic simulation: 2070 to 2120
  Harvest ratio: 0.75
  Clearfell/thinning split: {'DISTID1': 0.8, 'DISTID2': 0.2}
  Year 2080 complete
  Year 2090 complete
  Year 2100 complete
  Year 2110 complete
  Year 2120 complete
Dynamic simulation complete: 50 years

,Year,AGB,BGB,Deadwood,Litter,Soil,Harvest,Total Ecosystem,Scenario
0,1991,7263.311101,1759.130211,8.504021,343.097664,-1734.363021,0.0,7639.679976,-1
1,1992,22253.850184,5250.505060,52.796405,1556.895918,-5776.696748,0.0,23337.350820,-1
2,1993,44303.328764,10481.865799,175.098926,3892.237344,-8829.050404,0.0,50023.480430,-1
3,1994,69440.947422,17314.024378,424.060031,7326.565980,-11232.248424,0.0,83273.349387,-1
4,1995,102710.631872,25607.246189,844.222681,11850.327134,-14254.706643,0.0,126757.721232,-1

In [9]:
dsg.export_archive('./dsg_simulation_archive.db')

The archive additionally stores the dynamic-continuation diagnostics: `dynamic_FM_nai_summary`, `dynamic_AF_nai_summary`, NAI history, and sustainability metrics.